const starterConfig = `{
  "$schema": "./schemas/openclaw.schema.json",
  "agent": {
    "model": "anthropic/claude-opus-4-6"
  },
  "gateway": {
    "port": 18789,
    "bind": "loopback"
  },
  "browser": {
    "enabled": true,
    "color": "#FF7A18"
  },
  "channels": {
    "discord": {
      "token": "env:DISCORD_BOT_TOKEN"
    }
  },
  "plugins": {
    "entries": {}
  }
}
`;

function toTitleCase(slug: string): string {
  return slug
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function createWorkspaceConfigTemplate(): string {
  return starterConfig;
}

export function createPluginFiles(pluginId: string): Array<{ path: string; content: string }> {
  const displayName = toTitleCase(pluginId);

  return [
    {
      path: `${pluginId}/openclaw.plugin.json`,
      content: `{
  "$schema": "../../schemas/openclaw.plugin.schema.json",
  "id": "${pluginId}",
  "name": "${displayName}",
  "description": "A starter OpenClaw plugin scaffolded by OpenClawd Studio.",
  "version": "0.1.0",
  "configSchema": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "enabled": {
        "type": "boolean",
        "default": true
      }
    }
  }
}
`
    },
    {
      path: `${pluginId}/package.json`,
      content: `{
  "name": "${pluginId}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc -p tsconfig.json"
  },
  "devDependencies": {
    "typescript": "^5.9.2"
  }
}
`
    },
    {
      path: `${pluginId}/tsconfig.json`,
      content: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "skipLibCheck": true
  },
  "include": [
    "src/**/*.ts"
  ]
}
`
    },
    {
      path: `${pluginId}/src/index.ts`,
      content: `export interface ${displayName.replace(/\s+/g, "")}Config {
  enabled?: boolean;
}

export function createPlugin() {
  return {
    id: "${pluginId}",
    setup(config: ${displayName.replace(/\s+/g, "")}Config = {}) {
      return {
        enabled: config.enabled ?? true
      };
    }
  };
}
`
    },
    {
      path: `${pluginId}/README.md`,
      content: `# ${displayName}

Generated by OpenClawd Studio.

## Next steps

1. Add your runtime code in \`src/index.ts\`.
2. Expand \`openclaw.plugin.json\` with channel or provider metadata.
3. Build with \`npm run build\`.
4. Wire the plugin into your OpenClaw workspace configuration.
`
    }
  ];
}
